apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: drych-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drych-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: drych-volume
        persistentVolumeClaim:
          claimName: drych

