apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  namespace: drych-namespace
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: drych-volume
      mountPath: /mnt
  volumes:
  - name: drych-volume
    persistentVolumeClaim:
      claimName: drych

