apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deployment
   namespace: drych-namespace  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: drych-nginx
        image: drych/drych-nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
