---
- import_role:
    name: common

- name: Ensure /etc/prometheus directory exists
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    state: started
    restart_policy: unless-stopped
    
